---
title: "Scottland, UK"
author: "Blake Greene"
date: "2024-11-03"
categories: [travel]
draft: true
---

## Scottland, UK - May 2023 {.tabset}

### Day 0
Tuesday 9 May 2023
GSP -> ATL -> AMS

Quick trip through security and breakfast at Chick-fil-a. What a bad biscuit. It's sweet.

The layover in Atlanta was rough. Got super bored and was very tired. Tried not to sleep too much so I could sleep on the the next flight. Bad idea.

Flight to Amsterdam went well, but the second half definitely seemed to drag on forever. And the guy behind me pounded on the TV screen like he was trying to break it. Obviously I didn't sleep much.

### Day 1
Wednesday, 10 May 2023
AMS -> EDI & Edinburgh
I had a quick layover in Amsterdam this morning for about 2 hours.
I grabbed some coffee and did some pleasure reading and a Duolingo lesson.
It's easy to forget how much I enjoy reading a good book when I'm used to spending so much time reading journal articles and research papers which I'm not always really interested in.
I've also been learning German over the last few years.
I haven't been progressing very quickly, but a few minutes each day keeps me interested and moving forward.

The flight to Edinburgh was quick and I had an interesting "cheese salad" sandwich on the plane.
It was a Duth brand and the package claimed it was a traditional sandwich in the Netherlands. 
I have to say, I was pleasantly surprised with how good it was.
When I landed in Amsterdam, I didn't feel like I was in another country yet.
It's something about being in an airport where, to me, it feels like I'm existing in a place outside of normal space and time.
I feel like I'm inside some sort of travel portal, zipping from hub to hub in a somewhat cramped little vehicle.
It truly is a surreal experience every time to me, especially overnight flights where you can't see the geography passing by outside, and I tend to choose aisle seats so I can get up and walk around without disturbing my neighboring travelers.

My first impression of Edinburgh was how beautiful the buildings are.
To me, it highlighted the age of the city and how much history this city has.
I walked to my hostel to drop off my bag and take a shower.
To be frank, I smelled bad.
Spending two and a half days in airports without a shower had taken a toll on me.

Once I was refreshed and ready for the outside world, I talked to the desk attendant at the hostel.
When I have traveled in the States, I like talking to the locals about their favorite places for food and drinks.
This has (almost) always served me well and I tend to learn about hidden gems that you won't easily find with a Google search.
The attendant suggested a small cafe down the street - especially since they also would serve me a beer if I wanted one.
Turns out, I wasn't ready for a beer yet. 
I hadn't really slept much in the last two nights (airplanes are not an easy place for me to sleep, and neither are airport floors) and I needed fuel more than fun.
Coffee, lentil soup, and fresh bread sounded great and turned out to be just what I needed.
Now that I was properly fueled and refreshed, I felt like I was ready to explore the city.

My first stop was the National Library and National Museum of Scottland, both of which are free and open to the public.
I love museums, they satisfy my curiosity and love for science and history.
Unfortunately in this case, I was so tired I really couldn't focus on the exhibits.
Turns out that I wasn't as fueled and ready for exploration as I had thought so I decided I could come back when I circled back to Edinburgh next week.

I figured if I was too tired to enjoy the museums, then I could at least find some refuge in an old pub and get my history lesson for the day that way.
My first stop was The White Heart Inn which claims to be the oldest tavern in Edinburgh (founded in 1516 C.E.).
My next stop was The Last Drop - named for the fact that, in the 1800s, one of the city's primary gallows was located nearby.
The streets around this area are much less macabre now, with many bright shops, businesses, and restaurants, but I was craving a dark corner table and a cold, tasty beer and another hot meal.
Chicken, bacon, mashed potatoes, haggis, gravy, and steamed vegetables.
It was such a satisfying meal - delicious, flavorful, and filling.
Next stop: sleep.

### Day 2
Thursday, 11 May 2023
Edinburgh & Glasgow

Foot feeling better! Still sore, but more walkale today.
Slepts almost 11 hours.
Feel much better today.
Breakfast in the hostel lounge.

Walked up to Capitol Hill around 8:00. 
Great view of Edinburgh and Forth Upon Firth.
After looking at Arthur's Seat, I decided to hike it next week before I leave.

9:30 ticket to Edinburgh Castle. Quite crowded.
Tourist don't know how to que. Beautiful views and great history, but ran out of time - had to run through War Museum.
Train to Glasgow at 11:45.

Visited Galsgow Cathedral, St. Mungo's Museum, Glasgow Necropolis, and the Southern Necropolis. 
Lots of walking.
Also took a look at McLennan Arch beore going to The Scotia.
Talked to a guy from Australia (Brian) and a couple locals.
Local fellas brought up "Wuhan Flu" and "freedom to travel".
Noped out of that convo real quick.

Going to Stirling Castle tomorrow on Brian's Recommendation.

### Day 3
Friday, 12 May 2023
Glasgow and Stirling

Day trip to Stirling - Stirling Castle and National Wallace Monument.
Also saw the Beheading Stone on my walk from the castle to the monument.

Tons of really cool history at the castle.
Monument was cool, but not sure it was worth 10 pounds.

Feet killing me by end of day.
Long walk from train to Airbnb, then to Finneston St., but I made it.

Gary's place was cool.
Small, but nice and efficient.
Big Terry Pratchett fan.

Bed pretty early.

### Day 4
Saturday, 13 May 2023
Glasgow and Inverness

Checked out early and walked to Kelvingrove Park. Bought hot coffee along the way. Park is really nice. Lots of statues and monuments. Including one of Lord Kelvin. Also saw a stray pup with a dead pigeon for a prize.

Hunterian Museum next. Another free one. Pre-history, Pre-Roman, Roman, more. Also fossils, medical history, and all sorts of science history from Lord Kelvin. Really cool stuff.

Tall Ship Glenlee in the afternoon. Late 19th century, early 20th century cargo vessel. Took tons of pics to turn into scans.

Rest of the afternoon at a couple different pubs. Gallus and Waxy O'Connors. Waxy was really cool inside - many levels at strange heights and arrangements - real Hogwarts vibe.

Train to Inverness just before 6. Tons of sreaming kids first hour of 2nd leg. An no AC/power on the carrages. Then the plugs in the hostel dorm are EU! So nothing charging overnight. Also worst smelling shower I've ever been in.

### Day 5
Sunday, 14 May 2023
Inverness
Took a bus to Culloden Battlefield on Dave K's advice. Super cool visit, lots to learn. Also beautiful 30 minute walk between the closest bus stop and the battlefield with great views of the countryside.

Always blown away by how people are so irreverent at memorial sites. But all you can do is set an example, so that's what I did.

Quite cold all day, very windy.

Hit a funk in the afternoon. Didn't have set plans, so I wandered in town before trying a few pubs then heading to the hostel.

Felt like I was wasting my trip a couple times when I haven't been 100% on the go. More guilty than anything. I think next time I'll look for more hiking opportunities before setting off. It's easy to forget how much I enjoy hiking and walking in new and beautiful places. So I'm going to a get a good walk or 3 in tomorrow.

### Day 6
Monday, 15 May 2023
Inverness

Hopped on a bus to Urquhart Castle. Really gool ruins on the shore of Loch Ness. No monster sightings, though. Sign at the castle said Loch Ness is more than 200 meters deep in the middle close to the castle ruins. WIld.

Walked into town and found trail to water fall. Beautiful little diversion. Continued with a few other scenic hikes before walking back to castle to catch bus.

Hit up a few local pubs, listened to a local band, and had leftovers for dinner. Bed around 10.

Realized how much I enjoy hiking in the UK. Tons of well maintained trails right by towns. Planning to do more hiking and walking before I leave.

### Day 7
Tuesday, 16 May 2023
Edinburgh

Hopped right on a train to Edinburgh before 9. Beautiful ride through the countryside.

Straight to hostel for check-in, then off for a hike. Corbies Craig, Hermitage of Braid, and Royal Observatory all in the same park! If feet and time weren't an issue I could've walked a lot further.

Beautiful view from top of Corbies. Excited to hike Arthur's Seat tomorrow.

Next trip I will plan for more hiking. Will also acquire topo maps, compas, and gps for safety.

### Day 8
Wednesday, 17 May 2023
Edinburgh

It has become increasingly obvious to me that I am searching for something. I don't know what it is yet, but the journey has been interesting to say the least. I know I won't find it in a place, but seeing some place new has sure been thought provoking.

Hiked around the Salisbury Craigs and Arthur's Seat before walking to Craigmiller Castle. More ruins than castle, but still reeally cool. Bought book on Scottish history at the museum shop.

Long walk back into town. Feet hurt. Had Scottish pulled pork sandwich for lunch. Meat was tasty, but not a big fan of the sauce.

Walked to Royal Botanic Gardens after lunch. 

Sometimes you just have to smile and the world gets brighter. 

Tons of walking today (20.6 miles?). Well deserved beers after dinner. Talked to a fella from Reno and one from Stirling while at The Blue Blazer.

### Day 9
Thursday, 18 May 2023
Edinburgh, EDI -> AMS -> ATL -> GSP

Walked up to Calton Hill area and looked at a few graveyards before catching an airport bus. Saw only American Civil War monument built outside of the United States.

Flight to Amsterdam was uneventful, if slightly delayed. A little turbulence. The flight to Atlant was also delayed, so no issues with layover. A little more turbulence heading to Atlanta than on the first flight, but not too bad.

